# CMake generated Testfile for 
# Source directory: /home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1
# Build directory: /home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EmptyTree.InsertNode_NoInsert "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.InsertNode_NoInsert")
add_test(EmptyTree.InsertNode_OneElement "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.InsertNode_OneElement")
add_test(EmptyTree.InsertNode_MoreWithoutRotation "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.InsertNode_MoreWithoutRotation")
add_test(EmptyTree.InsertNode_MoreWithRotation "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.InsertNode_MoreWithRotation")
add_test(EmptyTree.InsertNode_InserAndDelete "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.InsertNode_InserAndDelete")
add_test(EmptyTree.DeleteNode "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.DeleteNode")
add_test(EmptyTree.FindNode "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=EmptyTree.FindNode")
add_test(NonEmptyTree.InsertNode "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=NonEmptyTree.InsertNode")
add_test(NonEmptyTree.DeleteNode "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=NonEmptyTree.DeleteNode")
add_test(NonEmptyTree.FindDone "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=NonEmptyTree.FindDone")
add_test(TreeAxioms.Axiom1 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=TreeAxioms.Axiom1")
add_test(TreeAxioms.Axiom2 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=TreeAxioms.Axiom2")
add_test(TreeAxioms.Axiom3 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/black_box_test" "--gtest_filter=TreeAxioms.Axiom3")
add_test(TestMatrix.CreateMatrix "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=TestMatrix.CreateMatrix")
add_test(TestMatrix.CreateMatrixByVector "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=TestMatrix.CreateMatrixByVector")
add_test(SingleMatrix.Matrix1X1 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=SingleMatrix.Matrix1X1")
add_test(SolveEquations.Matrix1X1 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=SolveEquations.Matrix1X1")
add_test(SolveEquations.Matrix2X2 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=SolveEquations.Matrix2X2")
add_test(SolveEquations.Matrix3X3 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=SolveEquations.Matrix3X3")
add_test(SolveEquations.Matrix4X4 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=SolveEquations.Matrix4X4")
add_test(SolveEquations.Matrix3X4 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=SolveEquations.Matrix3X4")
add_test(MultipyOperation.Matrix1X1 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=MultipyOperation.Matrix1X1")
add_test(MultipyOperation.Matrix3X3 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=MultipyOperation.Matrix3X3")
add_test(MultipyOperation.FailMultiply "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=MultipyOperation.FailMultiply")
add_test(MultipyOperation.Matrix1X1ConstValue "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=MultipyOperation.Matrix1X1ConstValue")
add_test(MultipyOperation.Matrix3X3ConstValue "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=MultipyOperation.Matrix3X3ConstValue")
add_test(AddOperation.Matrix1X1 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=AddOperation.Matrix1X1")
add_test(AddOperation.Matrix3X3 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=AddOperation.Matrix3X3")
add_test(AddOperation.Matrix3X3_add_1X1 "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/white_box_test" "--gtest_filter=AddOperation.Matrix3X3_add_1X1")
add_test(NonEmptyQueue.Insert "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=NonEmptyQueue.Insert")
add_test(NonEmptyQueue.RemoveAllForward "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=NonEmptyQueue.RemoveAllForward")
add_test(NonEmptyQueue.RemoveAllBackward "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=NonEmptyQueue.RemoveAllBackward")
add_test(NonEmptyQueue.Find "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=NonEmptyQueue.Find")
add_test(EmptyQueue.Insert "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=EmptyQueue.Insert")
add_test(EmptyQueue.Remove "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=EmptyQueue.Remove")
add_test(EmptyQueue.Find "/home/martin/Plocha/IVS-VUT-BIT-2018-PROJ1/tdd_test" "--gtest_filter=EmptyQueue.Find")
subdirs(googletest-build)
